### ISSUE TITLE
unable to save to ./knowl/

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP3#5]
```
Traceback (most recent call last):
  File "./buildHTML.py", line 183, in <module>
    htmlSource = transform(procd, **param)
  File "src/lxml/xslt.pxi", line 600, in lxml.etree.XSLT.__call__
lxml.etree.XSLTApplyError: xsltDocumentElem: unable to save to ./knowl/p-122.html
```

**Comment by arechnitzer** [comment]
@cbm755 can you try-try this. Close if satisfied.

**Comment by cbm755** [comment]
Cannot reproduce this so closing.
